from __future__ import annotations

"""Pydantic models for CrewAI agent outputs."""

from pydantic import BaseModel
from pydantic import Field


class JobAnalysisResult(BaseModel):
    """Result from job description analysis by Job Analyzer Agent."""

    required_skills: list[str] = Field(
        description="List of required/must-have skills from job description"
    )
    preferred_skills: list[str] = Field(
        description="List of preferred/nice-to-have skills from job description"
    )
    key_responsibilities: list[str] = Field(
        description="Main responsibilities and duties for this role (top 5-7)"
    )
    role_level: str = Field(
        description="Seniority level (e.g., Junior, Mid, Senior, Staff, Principal, Director)"
    )
    role_type: str = Field(
        description="Primary role type (e.g., SRE, SDET, QE Leadership, DevOps Engineer)"
    )
    company_culture_notes: str = Field(
        default="",
        description="Cultural indicators or values mentioned in job description"
    )


class ExperienceEntry(BaseModel):
    """A single work experience entry with tailored achievements."""

    company: str = Field(description="Company name")
    title: str = Field(description="Job title")
    location: str | None = Field(default=None, description="Location (optional)")
    start_date: str = Field(description="Start date in YYYY-MM-DD format")
    end_date: str | None = Field(default=None, description="End date (None if current)")
    current: bool = Field(default=False, description="Is this current role?")
    achievements: list[str] = Field(
        description="Achievement bullets tailored to target job"
    )
    technologies: list[str] = Field(
        default_factory=list,
        description="Key technologies used in this role"
    )


class SkillEntry(BaseModel):
    """A single skill with categorization."""

    name: str = Field(description="Skill name")
    category: str | None = Field(default=None, description="Skill category")
    proficiency: str | None = Field(default=None, description="Proficiency level")


class ResumeContent(BaseModel):
    """Complete resume content generated by Content Generator Agent."""

    header_title: str = Field(
        description="Professional title for resume header (e.g., 'Senior SDET | Quality Engineering Leader')"
    )
    summary: str = Field(
        description="Professional summary paragraph tailored to target job"
    )
    experiences: list[ExperienceEntry] = Field(
        description="Work experience entries with tailored achievement bullets"
    )
    skills: list[SkillEntry] = Field(
        description="Skills list organized by category and prioritized for target job"
    )


class QualityReview(BaseModel):
    """Quality review result from Content Reviewer Agent."""

    passes_review: bool = Field(
        description="Whether content passes quality review"
    )
    alignment_score: int = Field(
        ge=1,
        le=10,
        description="How well resume aligns with job requirements (1-10)"
    )
    style_compliance_score: int = Field(
        ge=1,
        le=10,
        description="How well content follows style guidelines (1-10)"
    )
    issues_found: list[str] = Field(
        default_factory=list,
        description="Specific issues found with examples"
    )
    suggestions: list[str] = Field(
        default_factory=list,
        description="Constructive suggestions for improvement"
    )
    strengths: list[str] = Field(
        default_factory=list,
        description="Strong points in the resume content"
    )


class CoverLetter(BaseModel):
    """Cover letter generated by Cover Letter Agent."""

    opening_paragraph: str = Field(
        description="Opening paragraph with hook related to company/role"
    )
    body_paragraphs: list[str] = Field(
        description="2-3 body paragraphs highlighting relevant achievements"
    )
    closing_paragraph: str = Field(
        description="Closing paragraph with call to action"
    )

    def to_markdown(self) -> str:
        """Convert cover letter to markdown format.

        Returns:
            Cover letter formatted as markdown
        """
        paragraphs = [
            self.opening_paragraph,
            *self.body_paragraphs,
            self.closing_paragraph,
        ]
        return "\n\n".join(paragraphs)


class ProfileGenerationResult(BaseModel):
    """Complete result from profile generation workflow."""

    profile_name: str = Field(description="Name of generated profile")
    job_analysis: JobAnalysisResult = Field(description="Job analysis results")
    resume_content: ResumeContent = Field(description="Generated resume content")
    quality_review: QualityReview = Field(description="Quality review results")
    cover_letter: CoverLetter = Field(description="Generated cover letter")
    iterations: int = Field(description="Number of generation iterations")
    total_duration_seconds: float = Field(
        default=0.0,
        description="Total generation time in seconds"
    )
